const initialProductState = {
    name: '',
    brand: '',
    category: '',
    price: 0,
    wattage: 0,
    description: '',
    images: [],
    color: '',
    model: '',
    screen: {
      size: 0,
      resolution: '',
      response_time: 0,
      refresh_rate: 0,
      panel_type: '',
      hdr: false,
      aspect_ratio: '',
    },
    benchmark: 0,
    speed: '',
    cores: 0,
    thread: 0,
    cache: 0,
    memory: '',
    type: '',
    form_factor: '',
    socket: '',
    max_memory: '',
    chipset: '',
    weight: 0,
    track_stock: false,
    stock: 0,
  };
  
  export default initialProductState;